//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGorusOneriSistemiApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GorusOneriSistemiDBEntities1 : DbContext
    {
        public GorusOneriSistemiDBEntities1()
            : base("name=GorusOneriSistemiDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<Durumlar> Durumlar { get; set; }
        public virtual DbSet<Talepler> Talepler { get; set; }
        public virtual DbSet<Tipler> Tipler { get; set; }
        public virtual DbSet<YetkiliBirimler> YetkiliBirimler { get; set; }
        public virtual DbSet<Yetkililer> Yetkililer { get; set; }
    }
}
