//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGorusOneriSistemiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talepler
    {
        public int talepId { get; set; }
        public Nullable<int> uyeId { get; set; }
        public Nullable<int> birimId { get; set; }
        public Nullable<int> durumId { get; set; }
        public Nullable<int> tipId { get; set; }
        public string talepBaslik { get; set; }
        public string talepMesaj { get; set; }
        public Nullable<System.DateTime> olusturulmaTarihi { get; set; }
        public string talepCevap { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Durumlar Durumlar { get; set; }
        public virtual Tipler Tipler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
