//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGorusOneriSistemiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.Talepler = new HashSet<Talepler>();
        }
    
        public int uyeId { get; set; }
        public string uyeAdSoyad { get; set; }
        public string uyeEmail { get; set; }
        public string uyeParola { get; set; }
        public Nullable<System.DateTime> uyelikTarihi { get; set; }
        public Nullable<bool> uyeAktiflik { get; set; }
        public string uyeTelefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talepler> Talepler { get; set; }
    }
}
