//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGorusOneriSistemiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkililer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yetkililer()
        {
            this.YetkiliBirimler = new HashSet<YetkiliBirimler>();
        }
    
        public int yetkiliId { get; set; }
        public string yekiliAd { get; set; }
        public string yetkiliParola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YetkiliBirimler> YetkiliBirimler { get; set; }
    }
}
