//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGorusOneriSistemiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiliBirimler
    {
        public int yetkiliBirimId { get; set; }
        public Nullable<int> yetkiliId { get; set; }
        public Nullable<int> birimId { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Yetkililer Yetkililer { get; set; }
    }
}
